from docx import Document
from docx.shared import Inches, Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH
import os
from pathlib import Path

def create_business_plan_template():
    """
    Create a basic Word document template for business plans with placeholders 
    that match our schema.
    """
    # Create document
    doc = Document()
    
    # Create template path
    templates_path = Path("backend/data/templates/docx")
    templates_path.mkdir(parents=True, exist_ok=True)
    
    # Set margins
    sections = doc.sections
    for section in sections:
        section.top_margin = Inches(1)
        section.bottom_margin = Inches(1)
        section.left_margin = Inches(1)
        section.right_margin = Inches(1)
    
    # Add title
    title = doc.add_heading('{{business_name}}', 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    # Add subtitle
    subtitle = doc.add_paragraph('{{tagline}}')
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    subtitle.style = 'Subtitle'
    
    # Add a line break
    doc.add_paragraph()
    
    # Business Overview section
    doc.add_heading('Business Overview', level=1)
    overview_para = doc.add_paragraph('Business Description: ')
    overview_para.add_run('{{business_description}}').italic = True
    
    # Add a line break
    doc.add_paragraph()
    
    # Contact Information
    doc.add_heading('Contact Information', level=2)
    contact_para = doc.add_paragraph('Primary Contact: ')
    contact_para.add_run('{{contact_name}}').bold = True
    contact_para.add_run(' | Email: {{contact_email}} | Phone: {{contact_phone}}')
    
    # Add a line break
    doc.add_paragraph()
    
    # Market Analysis section
    doc.add_heading('Market Analysis', level=1)
    market_para = doc.add_paragraph('Target Market: ')
    market_para.add_run('{{target_market}}').italic = True
    
    market_size_para = doc.add_paragraph('Market Size: ')
    market_size_para.add_run('{{market_size}} | Growth Rate: {{market_growth}}').italic = True
    
    doc.add_paragraph('Competitors:')
    
    # Add a line break
    doc.add_paragraph()
    
    # Products and Services section
    doc.add_heading('Products and Services', level=1)
    
    usp_para = doc.add_paragraph('Unique Selling Proposition: ')
    usp_para.add_run('{{usp}}').italic = True
    
    doc.add_paragraph('Product/Service Offerings:')
    
    # Add a line break
    doc.add_paragraph()
    
    # Financial Projections section
    doc.add_heading('Financial Projections', level=1)
    
    # Create a table for financial projections
    table = doc.add_table(rows=5, cols=2)
    table.style = 'Table Grid'
    
    # Set table headers
    table.cell(0, 0).text = 'Metric'
    table.cell(0, 1).text = 'Value'
    
    # Set table data
    table.cell(1, 0).text = 'Initial Investment Required'
    table.cell(1, 1).text = '{{initial_investment}}'
    
    table.cell(2, 0).text = 'Year 1 Revenue Target'
    table.cell(2, 1).text = '{{year1_revenue}}'
    
    table.cell(3, 0).text = 'Year 3 Revenue Target'
    table.cell(3, 1).text = '{{year3_revenue}}'
    
    table.cell(4, 0).text = 'Break-even Timeline'
    table.cell(4, 1).text = '{{breakeven_timeline}}'
    
    # Add funding strategy
    funding_para = doc.add_paragraph('Funding Strategy: ')
    funding_para.add_run('{{funding_strategy}}').italic = True
    
    # Add a line break
    doc.add_paragraph()
    
    # Team section
    doc.add_heading('Our Team', level=1)
    doc.add_paragraph('Key Team Members:')
    
    # Add a line break
    doc.add_paragraph()
    
    # Milestones section
    doc.add_heading('Milestones', level=1)
    doc.add_paragraph('Key Milestones:')
    
    # Add a line break
    doc.add_paragraph()
    
    # Risks section
    doc.add_heading('Risks and Mitigation', level=1)
    doc.add_paragraph('Key Risks:')
    
    # Add a line break
    doc.add_paragraph()
    
    # Add footer information
    footer_section = doc.sections[0]
    footer = footer_section.footer
    footer_para = footer.paragraphs[0]
    footer_para.text = "Generated by Nexus Business Builder | Contact: {{contact_name}} | {{contact_email}}"
    footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    # Save the document
    output_path = templates_path / "business_plan.docx"
    doc.save(output_path)
    
    print(f"Template created at: {output_path}")
    return output_path

if __name__ == "__main__":
    create_business_plan_template() 